# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e55951fc690e11bdfb6b12e989ba71b1633dee41a0dc18fafe596b465a7f5a48b2f8e0b54016533e05915f6ccc6a115fbd685cbdd21261eb9610370a93ac82e

test:
  secret_key_base: 6a878f849c31328cc0b0d74b23c6cce7302e2eb1c8be9d759b41fae646db4e95f0b751bbd9ed1ed1c9374d53343fd10bd48990a95cd3c5f60826acc0eed398f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
